client:
  consumer_key: "Your Consumer Key"
  consumer_secret: "Your Consumer Secret Key"
  access_token: "Your Access Token"
  access_token_secret: "Your Access Token Secret"
  
users:
  - "todesking"
  - "toby_net"
  - "doom_k"
  - "tadsan"
  - "ntddk"
  - "drillbits"
  - "mizchi"
